siteName: test assemble demo
footerLinks:
  - title: test
    url: http://www.codegrid.net/
  - title: github repository
    url: https://github.com/pxgrid/codegrid-assemble
  - title: PixelGrid
    url: http://www.pxgrid.com/